apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-sak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 600Mi
  vault:
    enabled: false
  filesFrom:
    - secret: pale2-google-creds
  webproxy: false
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: pale-2-pdfgen
          namespace: teamsykmelding
          cluster: prod-gcp
      external:
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: syfohelsenettproxy.prod-fss-pub.nais.io
  env:
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: PALE_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-pale2-vedlegg-bucket-prod
    - name: PALE_BUCKET_NAME
      value: teamsykmelding-pale2-legeerklaring-bucket-prod
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.prod-fss-pub.nais.io
    - name: HELSENETT_SCOPE
      value: api://prod-fss.teamsykmelding.syfohelsenettproxy/.default
