apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-sak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 700Mi
  filesFrom:
    - secret: pale2-google-creds
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: pale-2-pdfgen
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfohelsenettproxy
      external:
        - host: dokarkiv.prod-fss-pub.nais.io
  envFrom:
    - secret: pale-2-secret
  env:
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: HELSENETT_SCOPE
      value: api://prod-gcp.teamsykmelding.syfohelsenettproxy/.default
