apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-sak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/pale-2-sak/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  ingresses:
    - "https://pale-2-sak.nais.adeo.no"
  env:
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.intern.nav.no/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: PALE_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-pale2-vedlegg-bucket-prod
    - name: PALE_BUCKET_NAME
      value: teamsykmelding-pale2-legeerklaring-bucket-prod