apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-sak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvpale2sak
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/pale-2-sak/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  ingresses:
    - "https://pale-2-sak.nais.preprod.local"
  env:
    - name: DOK_ARKIV_URL
      value: https://dokarkiv-q1.nais.preprod.local/rest/journalpostapi/v1/journalpost
    - name: OPPRETT_SAK_URL
      value: https://sak-q1.dev.intern.nav.no/api/v1/saker
    - name: PALE_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-pale2-vedlegg-bucket-dev
    - name: PALE_BUCKET_NAME
      value: teamsykmelding-pale2-legeerklaring-bucket-dev