apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-sak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 600Mi
  filesFrom:
    - secret: pale2-google-creds
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: pale-2-pdfgen
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfohelsenettproxy
      external:
        - host: dokarkiv.dev-fss-pub.nais.io
  env:
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
    - name: PALE_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-pale2-vedlegg-bucket-dev
    - name: PALE_BUCKET_NAME
      value: teamsykmelding-pale2-legeerklaring-bucket-dev
    - name: HELSENETT_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
